//! GUT v1 Protocol - TC/XDP eBPF Fast Path Loader
//!
//! This loader manages eBPF programs for GUT v1 protocol with auto-detection
//! of the best redirect mode:
//!
//! **Level 1**: veth + XDP devmap bulk redirect + native XDP
//!   - Fastest: eliminates TC stage, kernel batches NAPI redirects
//!   - Requires NIC driver with XDP native support
//!
//! **Level 2**: veth + XDP devmap bulk redirect + generic XDP  
//!   - Same devmap benefit, but XDP runs in generic/SKB mode
//!   - When NIC lacks native XDP driver support
//!
//! **Level 3**: TAP + XDP_PASS + TC redirect (fallback)
//!   - Works on any kernel ≥ 5.2
//!   - Two-stage: XDP decap → TC bpf_redirect(TAP, BPF_F_INGRESS)
//!
//! Levels 1-2 use the same BPF program (xdp_gut_ingress_devmap).
//! The kernel auto-selects native vs generic XDP at attach time.
//!
//! Responsibilities:
//! - Create data interface (veth pair or TAP)
//! - Load compiled eBPF .o files (generated by libbpf-cargo in build.rs)
//! - Attach TC hooks: egress (TUN→UDP) and ingress (UDP→TUN)
//! - Initialize BPF maps with GUT v1 config
//! - Read statistics from BPF maps

use crate::config::Config;
use crate::netlink::{
    get_ifindex, hex16, link_set_gso_max_size, lookup_arp_cache, lookup_ndp_cache,
    probe_neighbor_udp, read_gso_max_size, read_mac, read_mtu,
};
use crate::tc::maps::{
    GutConfig, GutStats, TcDebugStats, DEFAULT_INNER_MTU, GUT_FLAG_NEED_L4_CSUM, OUTER_OVERHEAD_IPV4,
    OUTER_OVERHEAD_IPV6,
};
use crate::Result;
use std::os::fd::AsRawFd;
use std::sync::atomic::Ordering;
#[cfg(not(target_has_atomic = "64"))]
use std::sync::Mutex;

#[cfg(target_has_atomic = "64")]
type CounterInner = std::sync::atomic::AtomicU64;
#[cfg(not(target_has_atomic = "64"))]
type CounterInner = Mutex<u64>;

struct CounterU64 {
    inner: CounterInner,
}

impl CounterU64 {
    const fn new(value: u64) -> Self {
        #[cfg(target_has_atomic = "64")]
        {
            Self {
                inner: std::sync::atomic::AtomicU64::new(value),
            }
        }
        #[cfg(not(target_has_atomic = "64"))]
        {
            Self {
                inner: Mutex::new(value),
            }
        }
    }

    fn fetch_add(&self, value: u64, ordering: Ordering) -> u64 {
        #[cfg(target_has_atomic = "64")]
        {
            self.inner.fetch_add(value, ordering)
        }
        #[cfg(not(target_has_atomic = "64"))]
        {
            let _ = ordering;
            let mut guard = self.inner.lock().expect("counter mutex poisoned");
            let old = *guard;
            *guard = old.saturating_add(value);
            old
        }
    }

    fn load(&self, ordering: Ordering) -> u64 {
        #[cfg(target_has_atomic = "64")]
        {
            self.inner.load(ordering)
        }
        #[cfg(not(target_has_atomic = "64"))]
        {
            let _ = ordering;
            *self.inner.lock().expect("counter mutex poisoned")
        }
    }
}

static DROP_POLICY_SAFETY_OVERRIDES: CounterU64 = CounterU64::new(0);

#[must_use]
pub fn drop_policy_safety_overrides() -> u64 {
    DROP_POLICY_SAFETY_OVERRIDES.load(Ordering::Relaxed)
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
use std::mem::MaybeUninit;

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
use std::os::fd::AsFd;

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
use libbpf_rs::skel::{OpenSkel, SkelBuilder};

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
use libbpf_rs::{MapCore, MapFlags, TcHookBuilder};

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
#[allow(clippy::all, clippy::pedantic)]
mod tc_gut_egress {
    include!(concat!(env!("OUT_DIR"), "/tc_gut_egress.skel.rs"));
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
#[allow(clippy::all, clippy::pedantic)]
mod tc_gut_egress_v6 {
    include!(concat!(env!("OUT_DIR"), "/tc_gut_egress_v6.skel.rs"));
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
#[allow(clippy::all, clippy::pedantic)]
mod xdp_gut_ingress {
    include!(concat!(env!("OUT_DIR"), "/xdp_gut_ingress.skel.rs"));
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
#[allow(clippy::all, clippy::pedantic)]
mod tc_gut_egress_quic {
    include!(concat!(env!("OUT_DIR"), "/tc_gut_egress_quic.skel.rs"));
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
#[allow(clippy::all, clippy::pedantic)]
mod tc_gut_egress_quic_v6 {
    include!(concat!(env!("OUT_DIR"), "/tc_gut_egress_quic_v6.skel.rs"));
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
#[allow(clippy::all, clippy::pedantic)]
mod xdp_gut_ingress_quic {
    include!(concat!(env!("OUT_DIR"), "/xdp_gut_ingress_quic.skel.rs"));
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
#[allow(clippy::all, clippy::pedantic)]
mod tc_gut_egress_syslog {
    include!(concat!(env!("OUT_DIR"), "/tc_gut_egress_syslog.skel.rs"));
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
#[allow(clippy::all, clippy::pedantic)]
mod tc_gut_egress_syslog_v6 {
    include!(concat!(env!("OUT_DIR"), "/tc_gut_egress_syslog_v6.skel.rs"));
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
#[allow(clippy::all, clippy::pedantic)]
mod xdp_gut_ingress_syslog {
    include!(concat!(env!("OUT_DIR"), "/xdp_gut_ingress_syslog.skel.rs"));
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
#[allow(clippy::all, clippy::pedantic)]
mod tc_gut_egress_sip {
    include!(concat!(env!("OUT_DIR"), "/tc_gut_egress_sip.skel.rs"));
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
#[allow(clippy::all, clippy::pedantic)]
mod tc_gut_egress_sip_v6 {
    include!(concat!(env!("OUT_DIR"), "/tc_gut_egress_sip_v6.skel.rs"));
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
#[allow(clippy::all, clippy::pedantic)]
mod xdp_gut_ingress_sip {
    include!(concat!(env!("OUT_DIR"), "/xdp_gut_ingress_sip.skel.rs"));
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
#[allow(clippy::all, clippy::pedantic)]
mod xdp_dispatcher {
    include!(concat!(env!("OUT_DIR"), "/xdp_dispatcher.skel.rs"));
}

/// Egress skeleton: mode × outer-AF variant.
/// Compiled from the same source with different -D flags.
#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
enum EgressSkel {
    V4(tc_gut_egress::TcGutEgressSkel<'static>),
    V6(tc_gut_egress_v6::TcGutEgressSkel<'static>),
    QuicV4(tc_gut_egress_quic::TcGutEgressSkel<'static>),
    QuicV6(tc_gut_egress_quic_v6::TcGutEgressSkel<'static>),
    SyslogV4(tc_gut_egress_syslog::TcGutEgressSkel<'static>),
    SyslogV6(tc_gut_egress_syslog_v6::TcGutEgressSkel<'static>),
    SipV4(tc_gut_egress_sip::TcGutEgressSkel<'static>),
    SipV6(tc_gut_egress_sip_v6::TcGutEgressSkel<'static>),
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
impl EgressSkel {
    fn update_config_map(&self, gut_config: &GutConfig) -> crate::Result<()> {
        let value = unsafe {
            std::slice::from_raw_parts(
                (gut_config as *const GutConfig).cast::<u8>(),
                std::mem::size_of::<GutConfig>(),
            )
        };
        match self {
            Self::QuicV4(s) => {
                s.maps
                    .config_map
                    .update(&0u32.to_ne_bytes(), value, MapFlags::ANY)?
            }
            Self::QuicV6(s) => {
                s.maps
                    .config_map
                    .update(&0u32.to_ne_bytes(), value, MapFlags::ANY)?
            }
            Self::V4(s) => s
                .maps
                .config_map
                .update(&0u32.to_ne_bytes(), value, MapFlags::ANY)?,
            Self::V6(s) => s
                .maps
                .config_map
                .update(&0u32.to_ne_bytes(), value, MapFlags::ANY)?,
            Self::SyslogV4(s) => {
                s.maps
                    .config_map
                    .update(&0u32.to_ne_bytes(), value, MapFlags::ANY)?
            }
            Self::SyslogV6(s) => {
                s.maps
                    .config_map
                    .update(&0u32.to_ne_bytes(), value, MapFlags::ANY)?
            }
            Self::SipV4(s) => {
                s.maps
                    .config_map
                    .update(&0u32.to_ne_bytes(), value, MapFlags::ANY)?
            }
            Self::SipV6(s) => {
                s.maps
                    .config_map
                    .update(&0u32.to_ne_bytes(), value, MapFlags::ANY)?
            }
        }
        Ok(())
    }

    fn update_counters_map(&self, initial_seq: u32) -> crate::Result<()> {
        let bytes = initial_seq.to_ne_bytes();
        match self {
            Self::QuicV4(s) => {
                s.maps
                    .counters_map
                    .update(&0u32.to_ne_bytes(), &bytes, MapFlags::ANY)?
            }
            Self::QuicV6(s) => {
                s.maps
                    .counters_map
                    .update(&0u32.to_ne_bytes(), &bytes, MapFlags::ANY)?
            }
            Self::V4(s) => {
                s.maps
                    .counters_map
                    .update(&0u32.to_ne_bytes(), &bytes, MapFlags::ANY)?
            }
            Self::V6(s) => {
                s.maps
                    .counters_map
                    .update(&0u32.to_ne_bytes(), &bytes, MapFlags::ANY)?
            }
            Self::SyslogV4(s) => {
                s.maps
                    .counters_map
                    .update(&0u32.to_ne_bytes(), &bytes, MapFlags::ANY)?
            }
            Self::SyslogV6(s) => {
                s.maps
                    .counters_map
                    .update(&0u32.to_ne_bytes(), &bytes, MapFlags::ANY)?
            }
            Self::SipV4(s) => {
                s.maps
                    .counters_map
                    .update(&0u32.to_ne_bytes(), &bytes, MapFlags::ANY)?
            }
            Self::SipV6(s) => {
                s.maps
                    .counters_map
                    .update(&0u32.to_ne_bytes(), &bytes, MapFlags::ANY)?
            }
        }
        Ok(())
    }

    fn gut_egress_fd(&self) -> std::os::fd::BorrowedFd<'_> {
        match self {
            Self::QuicV4(s) => s.progs.gut_egress.as_fd(),
            Self::QuicV6(s) => s.progs.gut_egress.as_fd(),
            Self::V4(s) => s.progs.gut_egress.as_fd(),
            Self::V6(s) => s.progs.gut_egress.as_fd(),
            Self::SyslogV4(s) => s.progs.gut_egress.as_fd(),
            Self::SyslogV6(s) => s.progs.gut_egress.as_fd(),
            Self::SipV4(s) => s.progs.gut_egress.as_fd(),
            Self::SipV6(s) => s.progs.gut_egress.as_fd(),
        }
    }

    fn is_v6(&self) -> bool {
        matches!(
            self,
            Self::QuicV6(_) | Self::V6(_) | Self::SyslogV6(_) | Self::SipV6(_)
        )
    }

    fn get_map_fd(&self, name: &str) -> Option<std::os::unix::io::BorrowedFd<'_>> {
        use std::os::unix::io::AsFd;
        macro_rules! map_fd {
            ($s:expr) => {
                match name {
                    "client_map" => Some($s.maps.client_map.as_fd()),
                    "session_map" => Some($s.maps.session_map.as_fd()),
                    "config_map" => Some($s.maps.config_map.as_fd()),
                    "counters_map" => Some($s.maps.counters_map.as_fd()),
                    "stats_map" => Some($s.maps.stats_map.as_fd()),
                    "tc_debug_map" => Some($s.maps.tc_debug_map.as_fd()),
                    "scratch_map" => Some($s.maps.scratch_map.as_fd()),
                    _ => None,
                }
            };
        }
        match self {
            Self::QuicV4(s) => map_fd!(s),
            Self::QuicV6(s) => map_fd!(s),
            Self::V4(s) => map_fd!(s),
            Self::V6(s) => map_fd!(s),
            Self::SyslogV4(s) => map_fd!(s),
            Self::SyslogV6(s) => map_fd!(s),
            Self::SipV4(s) => map_fd!(s),
            Self::SipV6(s) => map_fd!(s),
        }
    }

    /// Populate PROG_ARRAY map for QUIC/SIP tail-call split (kernel ≤6.2 compat).
    /// QUIC: gut_egress_quic_long → tc_progs[0]
    /// SIP:  gut_egress_sip_signal → tc_progs[0]
    fn setup_tail_call(&self) -> crate::Result<()> {
        use std::os::fd::AsRawFd;
        match self {
            Self::QuicV4(s) => {
                let fd = s.progs.gut_egress_quic_long.as_fd().as_raw_fd() as u32;
                s.maps
                    .tc_progs
                    .update(&0u32.to_ne_bytes(), &fd.to_ne_bytes(), MapFlags::ANY)?;
            }
            Self::QuicV6(s) => {
                let fd = s.progs.gut_egress_quic_long.as_fd().as_raw_fd() as u32;
                s.maps
                    .tc_progs
                    .update(&0u32.to_ne_bytes(), &fd.to_ne_bytes(), MapFlags::ANY)?;
            }
            Self::SipV4(s) => {
                let fd = s.progs.gut_egress_sip_signal.as_fd().as_raw_fd() as u32;
                s.maps
                    .tc_progs
                    .update(&0u32.to_ne_bytes(), &fd.to_ne_bytes(), MapFlags::ANY)?;
            }
            Self::SipV6(s) => {
                let fd = s.progs.gut_egress_sip_signal.as_fd().as_raw_fd() as u32;
                s.maps
                    .tc_progs
                    .update(&0u32.to_ne_bytes(), &fd.to_ne_bytes(), MapFlags::ANY)?;
            }
            _ => {} // GUT/Syslog modes don't use tail calls
        }
        Ok(())
    }

    fn lookup_stats(
        &self,
        key: &[u8],
    ) -> std::result::Result<Option<Vec<Vec<u8>>>, libbpf_rs::Error> {
        match self {
            Self::QuicV4(s) => s.maps.stats_map.lookup_percpu(key, MapFlags::ANY),
            Self::QuicV6(s) => s.maps.stats_map.lookup_percpu(key, MapFlags::ANY),
            Self::V4(s) => s.maps.stats_map.lookup_percpu(key, MapFlags::ANY),
            Self::V6(s) => s.maps.stats_map.lookup_percpu(key, MapFlags::ANY),
            Self::SyslogV4(s) => s.maps.stats_map.lookup_percpu(key, MapFlags::ANY),
            Self::SyslogV6(s) => s.maps.stats_map.lookup_percpu(key, MapFlags::ANY),
            Self::SipV4(s) => s.maps.stats_map.lookup_percpu(key, MapFlags::ANY),
            Self::SipV6(s) => s.maps.stats_map.lookup_percpu(key, MapFlags::ANY),
        }
    }
}

/// XDP attachment: bpf_link (preferred) or legacy netlink with explicit mode.
#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
#[allow(dead_code)] // Link held for Drop (auto-detach)
enum XdpAttachment {
    Link(libbpf_rs::Link),
    Legacy { ifindex: i32, flags: u32 },
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
impl Drop for XdpAttachment {
    fn drop(&mut self) {
        if let XdpAttachment::Legacy { ifindex, flags } = self {
            unsafe {
                libbpf_sys::bpf_xdp_detach(*ifindex, *flags, std::ptr::null());
            }
        }
    }
}

/// Per-NIC XDP dispatcher: routes packets by UDP dst_port to the
/// correct peer's XDP ingress program via tail-call.
/// One dispatcher per physical NIC, shared by all peers on that NIC.
#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
pub struct XdpDispatcher {
    _skel: xdp_dispatcher::XdpDispatcherSkel<'static>,
    _xdp_attach: XdpAttachment,
    next_peer_idx: u32,
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
impl XdpDispatcher {
    /// Load dispatcher and attach XDP to the given NIC.
    /// Tries bpf_link (auto native/generic), falls back to legacy SKB mode.
    pub fn new(ingress_ifindex: i32) -> crate::Result<Self> {
        let builder = xdp_dispatcher::XdpDispatcherSkelBuilder::default();
        let open_obj: &'static mut MaybeUninit<libbpf_rs::OpenObject> =
            Box::leak(Box::new(MaybeUninit::uninit()));
        let skel = builder.open(open_obj)?.load()?;

        // Detect NIC driver — some drivers (e.g. Xen vif) claim native XDP
        // support but their implementation is broken on certain kernels.
        // Force SKB mode for known-broken drivers.
        let force_skb = Self::should_force_skb(ingress_ifindex);
        if force_skb {
            eprintln!("    dispatcher: NIC driver requires SKB mode (known XDP issue)");
        }

        // Try bpf_link (auto-native) → legacy DRV → legacy SKB.
        // Native XDP is strongly preferred: devmap redirect from native XDP
        // to a veth with native XDP receiver is the only fully reliable path
        // on kernel 6.1+ (veth_xdp_xmit checks rq->xdp_prog).
        let xdp_attach = if force_skb {
            // Skip bpf_link and DRV, go straight to SKB
            use std::os::fd::AsRawFd;
            let prog_fd = skel.progs.xdp_dispatch.as_fd().as_raw_fd();
            let skb_flags = libbpf_sys::XDP_FLAGS_SKB_MODE;
            let ret_skb = unsafe {
                libbpf_sys::bpf_xdp_attach(ingress_ifindex, prog_fd, skb_flags, std::ptr::null())
            };
            if ret_skb < 0 {
                return Err(format!("XDP dispatcher SKB attach failed: errno {}", -ret_skb).into());
            }
            eprintln!("    dispatcher: attached via legacy SKB mode (forced)");
            XdpAttachment::Legacy {
                ifindex: ingress_ifindex,
                flags: skb_flags,
            }
        } else {
            match skel.progs.xdp_dispatch.attach_xdp(ingress_ifindex) {
                Ok(link) => {
                    eprintln!("    dispatcher: attached via bpf_link (native)");
                    XdpAttachment::Link(link)
                }
                Err(link_err) => {
                    eprintln!("    dispatcher: bpf_link XDP failed: {link_err}, trying legacy DRV");
                    use std::os::fd::AsRawFd;
                    let prog_fd = skel.progs.xdp_dispatch.as_fd().as_raw_fd();
                    let drv_flags = libbpf_sys::XDP_FLAGS_DRV_MODE;
                    let ret_drv = unsafe {
                        libbpf_sys::bpf_xdp_attach(
                            ingress_ifindex,
                            prog_fd,
                            drv_flags,
                            std::ptr::null(),
                        )
                    };
                    if ret_drv >= 0 {
                        eprintln!("    dispatcher: attached via legacy DRV (native) mode");
                        XdpAttachment::Legacy {
                            ifindex: ingress_ifindex,
                            flags: drv_flags,
                        }
                    } else {
                        eprintln!(
                            "    dispatcher: legacy DRV failed (errno {}), trying SKB",
                            -ret_drv
                        );
                        let skb_flags = libbpf_sys::XDP_FLAGS_SKB_MODE;
                        let ret_skb = unsafe {
                            libbpf_sys::bpf_xdp_attach(
                                ingress_ifindex,
                                prog_fd,
                                skb_flags,
                                std::ptr::null(),
                            )
                        };
                        if ret_skb < 0 {
                            return Err(format!(
                                "XDP dispatcher attach failed — bpf_link: {link_err}; \
                             DRV: errno {}; SKB: errno {}",
                                -ret_drv, -ret_skb
                            )
                            .into());
                        }
                        eprintln!(
                            "    WARNING: dispatcher in SKB mode — devmap redirect to native \
                         veth may silently drop packets on kernel 6.1+"
                        );
                        XdpAttachment::Legacy {
                            ifindex: ingress_ifindex,
                            flags: skb_flags,
                        }
                    }
                }
            }
        };
        Ok(Self {
            _skel: skel,
            _xdp_attach: xdp_attach,
            next_peer_idx: 0,
        })
    }

    /// Register a peer's XDP ingress program into the dispatcher.
    /// Inserts prog FD into xdp_peer_progs and all ports into port_map.
    /// Returns the assigned peer index.
    pub fn register_peer(&mut self, prog_raw_fd: i32, ports: &[u16]) -> crate::Result<u32> {
        let peer_idx = self.next_peer_idx;
        self.next_peer_idx += 1;
        let fd_val = prog_raw_fd as u32;
        self._skel.maps.xdp_peer_progs.update(
            &peer_idx.to_ne_bytes(),
            &fd_val.to_ne_bytes(),
            MapFlags::ANY,
        )?;
        for &port in ports {
            self._skel.maps.port_map.update(
                &port.to_ne_bytes(),
                &peer_idx.to_ne_bytes(),
                MapFlags::ANY,
            )?;
        }
        eprintln!("  dispatcher: peer_idx={peer_idx} ports={ports:?}");
        Ok(peer_idx)
    }

    /// Detect NIC drivers with broken native XDP implementations.
    /// Returns true if SKB mode should be forced.
    fn should_force_skb(ifindex: i32) -> bool {
        // Read driver name from sysfs: /sys/class/net/<ifname>/device/driver
        // or use ethtool-like ioctl. Simpler: read /sys/class/net/<ifname>/device/subsystem
        let ifname = match Self::ifindex_to_name(ifindex) {
            Some(name) => name,
            None => return false,
        };
        // Check driver via /sys/class/net/<ifname>/device/driver symlink
        let driver_path = format!("/sys/class/net/{ifname}/device/driver");
        if let Ok(target) = std::fs::read_link(&driver_path) {
            if let Some(driver) = target.file_name().and_then(|f| f.to_str()) {
                let broken_drivers = ["vif", "xen_netfront", "xen-netfront"];
                if broken_drivers.iter().any(|d| driver.contains(d)) {
                    eprintln!("    NIC {ifname}: driver={driver} — known broken native XDP");
                    return true;
                }
            }
        }
        // Also check parentbus from /sys/class/net/<ifname>/device/subsystem
        let subsystem_path = format!("/sys/class/net/{ifname}/device/subsystem");
        if let Ok(target) = std::fs::read_link(&subsystem_path) {
            if let Some(subsystem) = target.file_name().and_then(|f| f.to_str()) {
                if subsystem == "xen" {
                    eprintln!("    NIC {ifname}: subsystem=xen — forcing SKB mode");
                    return true;
                }
            }
        }
        false
    }

    /// Convert ifindex to interface name.
    fn ifindex_to_name(ifindex: i32) -> Option<String> {
        let entries = std::fs::read_dir("/sys/class/net/").ok()?;
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            let idx_path = format!("/sys/class/net/{name}/ifindex");
            if let Ok(content) = std::fs::read_to_string(&idx_path) {
                if content.trim().parse::<i32>().ok() == Some(ifindex) {
                    return Some(name);
                }
            }
        }
        None
    }
}

#[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
pub struct TcBpfManager {
    interface: String,
    ingress_interface: String,
    egress_skel: EgressSkel,
    _ingress_skel: Box<dyn std::any::Any>,
    _egress_hook: libbpf_rs::TcHook,
    _veth_pass_attach: XdpAttachment,
    _veth_xdp_name: String,
    ingress_stats_fd: i32,
}

#[cfg(not(all(target_os = "linux", feature = "tc_ebpf")))]
pub struct TcBpfManager {
    interface: String,
    ingress_interface: String,
}

#[derive(Debug, Default)]
pub struct TcStats {
    pub egress: GutStats,
    pub ingress: GutStats,
    pub debug: TcDebugStats,
}

#[cfg(target_os = "linux")]
struct RouteGetInfo {
    first_line: String,
    dev: Option<String>,
    via: Option<std::net::IpAddr>,
    src: Option<std::net::IpAddr>,
    mtu: Option<u16>,
}

impl TcBpfManager {
    /// Create veth pair, load and attach all BPF programs.
    ///
    /// Creates veth pair `<ifname>_xdp` ↔ `<ifname>`.
    /// Selects outer-IPv4 or outer-IPv6 egress BPF based on peer address family.
    /// Registers XDP ingress into the per-NIC dispatcher (created on first use).
    #[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
    pub fn new(
        ifname: &str,
        config: &Config,
        dispatchers: &mut std::collections::HashMap<String, XdpDispatcher>,
    ) -> Result<Self> {
        let ingress_ifname = if let Some(nic) =
            config.peer().nic.clone().filter(|s| !s.trim().is_empty())
        {
            nic
        } else if config.peer().dynamic_peer {
            // Dynamic peer: can't route-lookup 0.0.0.0; use default route.
            if let Some(default_ifname) = Self::default_route_ifname() {
                eprintln!(
                    "  Ingress NIC auto-detected from default route (dynamic peer): {}",
                    default_ifname
                );
                default_ifname
            } else {
                return Err(
                    "dynamic_peer: cannot auto-detect ingress NIC. Set 'nic' explicitly.".into(),
                );
            }
        } else if let Some(peer_ifname) = Self::route_get_info(config.peer().peer_ip)
            .ok()
            .and_then(|info| info.dev)
        {
            eprintln!(
                "  Ingress NIC auto-detected from route to peer {}: {}",
                config.peer().peer_ip,
                peer_ifname
            );
            peer_ifname
        } else if let Some(default_ifname) = Self::default_route_ifname() {
            eprintln!(
                "  Ingress NIC auto-detected from default route: {}",
                default_ifname
            );
            default_ifname
        } else {
            eprintln!(
                "  WARNING: could not auto-detect ingress NIC; falling back to {}",
                ifname
            );
            ifname.to_string()
        };

        let kernel_version = Self::check_kernel_version()?;
        if kernel_version < (5, 2, 0) {
            return Err(format!(
                "GUT TC eBPF requires kernel >= 5.2 (current: {}.{}.{})",
                kernel_version.0, kernel_version.1, kernel_version.2
            )
            .into());
        }

        let peer_is_v6 = config.peer().peer_ip.is_ipv6();
        let outer_af = if peer_is_v6 { "IPv6" } else { "IPv4" };
        eprintln!("GUT TC eBPF: Initializing (outer {outer_af})");
        eprintln!("  Egress (veth):    {ifname}");
        eprintln!("  Ingress (NIC):    {ingress_ifname}");

        // ── Create veth pair (MACs derived from tunnel IPs, static ARP) ─
        // Use outer_mtu (physical link MTU, e.g. 1500) for veth MTU, NOT the
        // WG inner MTU (e.g. 1420).  WG-encapsulated packets are up to
        // inner_mtu + 28 bytes of WG overhead; if the veth MTU equals the
        // inner MTU, IP forwarding drops or fragments those packets before
        // TC BPF ever sees them — causing 0 throughput on bulk data while
        // small control packets (handshake, keepalive, pings) still pass.
        let veth_xdp_name = format!("{ifname}_xdp");
        let (_local_mac, _xdp_mac) = crate::tun::create_veth_pair(
            ifname,
            &veth_xdp_name,
            config.peer().outer_mtu,
            Some(config.peer().address.as_str()),
        )?;
        eprintln!("  Created veth pair: {veth_xdp_name} ↔ {ifname}");
        let tun_mtu = Self::read_iface_mtu(ifname).ok();
        let xdp_mtu = Self::read_iface_mtu(&veth_xdp_name).ok();
        let tun_gso = Self::read_iface_gso_max_size(ifname).ok();
        let xdp_gso = Self::read_iface_gso_max_size(&veth_xdp_name).ok();
        eprintln!(
            "  Applied link caps: {} mtu={:?} gso_max_size={:?}; {} mtu={:?} gso_max_size={:?} (veth_mtu={}, wg_mtu={})",
            ifname,
            tun_mtu,
            tun_gso,
            veth_xdp_name,
            xdp_mtu,
            xdp_gso,
            config.peer().outer_mtu,
            config.peer().mtu
        );

        let tun_ifindex = Self::get_ifindex(ifname)?;
        let ingress_ifindex = Self::get_ifindex(&ingress_ifname)?;

        // Create or reuse per-NIC XDP dispatcher
        if !dispatchers.contains_key(&ingress_ifname) {
            let d = XdpDispatcher::new(ingress_ifindex)?;
            eprintln!("  XDP dispatcher attached on {ingress_ifname}");
            dispatchers.insert(ingress_ifname.clone(), d);
        }
        let dispatcher = dispatchers.get_mut(&ingress_ifname).unwrap();

        let gut_config = Self::build_gut_config(config, ifname, &ingress_ifname)?;
        let obfs_mode = config.peer().obfs;
        // gso_max_size = max total WireGuard packet (IP+UDP+WG_data) through gut0.
        // GUT TC BPF only *inserts* the 14-byte QUIC Short Header — the existing
        // WireGuard IP+UDP headers are moved back in-place (same size, rewritten).
        // So the net wire overhead is just +14 bytes, and gso_max_size must be:
        //   inner_mtu_v4 (max WG UDP payload) + IP_HDR(20) + UDP_HDR(8) = 1466
        let _gso_target = u32::from(gut_config.inner_mtu_v4) + 20 + 8;

        // For absolute consistency with eBPF egress logic, we must ensure gso_max_size
        // is high enough to allow any packet that BPF is willing to process.
        // 9000 is safer to avoid any kernel-level fragmentation of TSO/GSO segments
        // before they reach TC. eBPF datapath has enough memory (16KB) to handle this.
        let final_gso = 9000;

        Self::set_iface_gso_max_size(ifname, final_gso);
        Self::set_iface_gso_max_size(&veth_xdp_name, final_gso);
        eprintln!(
            "  Applied GSO cap: {}={} {}={} (gso_max_size)",
            ifname, final_gso, veth_xdp_name, final_gso
        );

        // ── Load egress skeleton (mode × AF) ──────────────────────────
        let egress_skel = match (obfs_mode, peer_is_v6) {
            (crate::config::ObfsMode::Gut, true) => {
                let b = tc_gut_egress_v6::TcGutEgressSkelBuilder::default();
                let o: &'static mut MaybeUninit<libbpf_rs::OpenObject> =
                    Box::leak(Box::new(MaybeUninit::uninit()));
                EgressSkel::V6(b.open(o)?.load()?)
            }
            (crate::config::ObfsMode::Gut, false) => {
                let b = tc_gut_egress::TcGutEgressSkelBuilder::default();
                let o: &'static mut MaybeUninit<libbpf_rs::OpenObject> =
                    Box::leak(Box::new(MaybeUninit::uninit()));
                EgressSkel::V4(b.open(o)?.load()?)
            }
            (crate::config::ObfsMode::Syslog, true) => {
                let b = tc_gut_egress_syslog_v6::TcGutEgressSkelBuilder::default();
                let o: &'static mut MaybeUninit<libbpf_rs::OpenObject> =
                    Box::leak(Box::new(MaybeUninit::uninit()));
                EgressSkel::SyslogV6(b.open(o)?.load()?)
            }
            (crate::config::ObfsMode::Syslog, false) => {
                let b = tc_gut_egress_syslog::TcGutEgressSkelBuilder::default();
                let o: &'static mut MaybeUninit<libbpf_rs::OpenObject> =
                    Box::leak(Box::new(MaybeUninit::uninit()));
                EgressSkel::SyslogV4(b.open(o)?.load()?)
            }
            (crate::config::ObfsMode::Sip, true) => {
                let b = tc_gut_egress_sip_v6::TcGutEgressSkelBuilder::default();
                let o: &'static mut MaybeUninit<libbpf_rs::OpenObject> =
                    Box::leak(Box::new(MaybeUninit::uninit()));
                EgressSkel::SipV6(b.open(o)?.load()?)
            }
            (crate::config::ObfsMode::Sip, false) => {
                let b = tc_gut_egress_sip::TcGutEgressSkelBuilder::default();
                let o: &'static mut MaybeUninit<libbpf_rs::OpenObject> =
                    Box::leak(Box::new(MaybeUninit::uninit()));
                EgressSkel::SipV4(b.open(o)?.load()?)
            }
            (_, true) => {
                let b = tc_gut_egress_quic_v6::TcGutEgressSkelBuilder::default();
                let o: &'static mut MaybeUninit<libbpf_rs::OpenObject> =
                    Box::leak(Box::new(MaybeUninit::uninit()));
                EgressSkel::QuicV6(b.open(o)?.load()?)
            }
            (_, false) => {
                let b = tc_gut_egress_quic::TcGutEgressSkelBuilder::default();
                let o: &'static mut MaybeUninit<libbpf_rs::OpenObject> =
                    Box::leak(Box::new(MaybeUninit::uninit()));
                EgressSkel::QuicV4(b.open(o)?.load()?)
            }
        };

        egress_skel.update_config_map(&gut_config)?;

        // Initialize seq counter
        egress_skel.update_counters_map(1)?;

        // Populate QUIC tail-call prog_array (no-op for non-QUIC modes)
        egress_skel.setup_tail_call()?;

        // Attach TC egress on veth user-side
        let mut tc_builder_egress = TcHookBuilder::new(egress_skel.gut_egress_fd());
        tc_builder_egress
            .ifindex(tun_ifindex)
            .replace(true)
            .handle(1)
            .priority(1);
        let mut egress_hook = tc_builder_egress.hook(libbpf_rs::libbpf_sys::BPF_TC_EGRESS);
        egress_hook.create()?;
        egress_hook.attach()?;
        eprintln!("  TC egress attached on {ifname} (outer {outer_af})");

        // ── Load ingress skeleton (mode-specific, XDP) ─────────────────
        let veth_xdp_ifindex = Self::get_ifindex(&veth_xdp_name)? as u32;
        macro_rules! load_ingress {
            ($mod:ident) => {{
                let builder = $mod::XdpGutIngressSkelBuilder::default();
                let open_obj: &'static mut MaybeUninit<libbpf_rs::OpenObject> =
                    Box::leak(Box::new(MaybeUninit::uninit()));
                let mut os = builder.open(open_obj)?;
                if let Some(fd) = egress_skel.get_map_fd("client_map") {
                    os.maps.client_map.reuse_fd(fd)?;
                }
                if let Some(fd) = egress_skel.get_map_fd("session_map") {
                    os.maps.session_map.reuse_fd(fd)?;
                }
                if let Some(fd) = egress_skel.get_map_fd("config_map") {
                    os.maps.config_map.reuse_fd(fd)?;
                }
                if let Some(fd) = egress_skel.get_map_fd("counters_map") {
                    os.maps.counters_map.reuse_fd(fd)?;
                }
                // stats_map is NOT shared — each program tracks its own stats
                if let Some(fd) = egress_skel.get_map_fd("scratch_map") {
                    os.maps.scratch_map.reuse_fd(fd)?;
                }
                let skel = os.load()?;
                skel.maps.tx_devmap.update(
                    &0u32.to_ne_bytes(),
                    &veth_xdp_ifindex.to_ne_bytes(),
                    MapFlags::ANY,
                )?;
                use std::os::fd::AsRawFd;
                let ingress_stats_fd = skel.maps.stats_map.as_fd().as_raw_fd();
                let ingress_prog_fd = skel.progs.xdp_gut_ingress.as_fd().as_raw_fd();
                // xdp_veth_pass MUST run in native (DRV) mode on the veth peer.
                // veth driver's ndo_xdp_xmit (used by devmap redirect from NIC XDP)
                // checks rcu_access_pointer(rq->xdp_prog) on the receiving end.
                // If only SKB-mode XDP is attached, this pointer is NULL and
                // devmap redirect silently drops ALL packets (kernel 6.1+).
                //
                // Attach order: bpf_link (auto-native) → legacy DRV → legacy SKB
                // (with warning that devmap redirect will fail).
                let vpl = match skel.progs.xdp_veth_pass.attach_xdp(tun_ifindex) {
                    Ok(link) => {
                        eprintln!("    veth_pass: attached via bpf_link (native)");
                        XdpAttachment::Link(link)
                    }
                    Err(link_err) => {
                        eprintln!(
                            "    veth_pass: bpf_link XDP failed: {link_err}, trying legacy DRV"
                        );
                        let vp_fd = skel.progs.xdp_veth_pass.as_fd().as_raw_fd();
                        // Try native (DRV) mode first — required for devmap redirect
                        let drv_flags = libbpf_sys::XDP_FLAGS_DRV_MODE;
                        let ret_drv = unsafe {
                            libbpf_sys::bpf_xdp_attach(
                                tun_ifindex,
                                vp_fd,
                                drv_flags,
                                std::ptr::null(),
                            )
                        };
                        if ret_drv >= 0 {
                            eprintln!("    veth_pass: attached via legacy DRV (native) mode");
                            XdpAttachment::Legacy {
                                ifindex: tun_ifindex,
                                flags: drv_flags,
                            }
                        } else {
                            eprintln!(
                                "    veth_pass: legacy DRV failed (errno {}), trying SKB",
                                -ret_drv
                            );
                            let skb_flags = libbpf_sys::XDP_FLAGS_SKB_MODE;
                            let ret_skb = unsafe {
                                libbpf_sys::bpf_xdp_attach(
                                    tun_ifindex,
                                    vp_fd,
                                    skb_flags,
                                    std::ptr::null(),
                                )
                            };
                            if ret_skb < 0 {
                                return Err(format!(
                                    "veth_pass XDP failed — bpf_link: {link_err}; \
                                     DRV: errno {}; SKB: errno {}",
                                    -ret_drv, -ret_skb
                                )
                                .into());
                            }
                            eprintln!(
                                "    WARNING: veth_pass in SKB mode — devmap redirect from \
                                 native XDP will silently drop packets on kernel 6.1+. \
                                 This is likely the cause of missing return packets."
                            );
                            XdpAttachment::Legacy {
                                ifindex: tun_ifindex,
                                flags: skb_flags,
                            }
                        }
                    }
                };
                dispatcher.register_peer(ingress_prog_fd, &config.peer().ports)?;
                (
                    Box::new(skel) as Box<dyn std::any::Any>,
                    vpl,
                    ingress_stats_fd,
                )
            }};
        }
        eprintln!("  devmap[0] = {veth_xdp_name} (ifindex={veth_xdp_ifindex})");

        let (_ingress_skel, veth_pass_link, ingress_stats_fd) = match obfs_mode {
            crate::config::ObfsMode::Gut => load_ingress!(xdp_gut_ingress),
            crate::config::ObfsMode::Syslog => load_ingress!(xdp_gut_ingress_syslog),
            crate::config::ObfsMode::Sip => {
                // SIP: use load_ingress! then populate xdp_progs tail-call map
                let (skel_box, vpl, stats_fd) = load_ingress!(xdp_gut_ingress_sip);
                {
                    use std::os::fd::AsRawFd;
                    let skel = skel_box
                        .downcast_ref::<xdp_gut_ingress_sip::XdpGutIngressSkel<'static>>()
                        .expect("SIP ingress skel downcast");
                    let fd = skel.progs.xdp_sip_probe.as_fd().as_raw_fd() as u32;
                    skel.maps.xdp_progs.update(
                        &0u32.to_ne_bytes(),
                        &fd.to_ne_bytes(),
                        MapFlags::ANY,
                    )?;
                }
                (skel_box, vpl, stats_fd)
            }
            _ => {
                // QUIC: use load_ingress! then populate xdp_progs tail-call map
                let (skel_box, vpl, stats_fd) = load_ingress!(xdp_gut_ingress_quic);
                {
                    use std::os::fd::AsRawFd;
                    let skel = skel_box
                        .downcast_ref::<xdp_gut_ingress_quic::XdpGutIngressSkel<'static>>()
                        .expect("QUIC ingress skel downcast");
                    let fd = skel.progs.xdp_quic_probe.as_fd().as_raw_fd() as u32;
                    skel.maps.xdp_progs.update(
                        &0u32.to_ne_bytes(),
                        &fd.to_ne_bytes(),
                        MapFlags::ANY,
                    )?;
                }
                (skel_box, vpl, stats_fd)
            }
        };

        let xdp_mode = Self::detect_xdp_mode(&ingress_ifname);
        let mode_name = match obfs_mode {
            crate::config::ObfsMode::Gut => "gut",
            crate::config::ObfsMode::Syslog => "syslog",
            crate::config::ObfsMode::Sip => "sip",
            _ => "quic",
        };
        eprintln!("  XDP ingress on {ingress_ifname} ({xdp_mode}, devmap → {veth_xdp_name})");
        eprintln!("GUT TC eBPF: Successfully attached (mode={mode_name})");

        Ok(Self {
            interface: ifname.to_string(),
            ingress_interface: ingress_ifname,
            egress_skel,
            _ingress_skel,
            _egress_hook: egress_hook,
            _veth_pass_attach: veth_pass_link,
            _veth_xdp_name: veth_xdp_name,
            ingress_stats_fd,
        })
    }

    /// Detect XDP mode (native/generic) by reading sysfs after attachment.
    #[cfg(target_os = "linux")]
    fn detect_xdp_mode(ifname: &str) -> &'static str {
        // Check /sys/class/net/<ifname>/xdp/mode or parse ip link output
        let path = format!("/sys/class/net/{ifname}/xdp");
        if std::path::Path::new(&path).exists() {
            // If xdp directory exists, XDP is attached
            // Check for drv_prog_id to determine if native
            let drv_path = format!("{path}/drv_prog_id");
            if let Ok(id) = std::fs::read_to_string(&drv_path) {
                let id = id.trim();
                if !id.is_empty() && id != "0" {
                    return "native/DRV";
                }
            }
            let skb_path = format!("{path}/skb_prog_id");
            if let Ok(id) = std::fs::read_to_string(&skb_path) {
                let id = id.trim();
                if !id.is_empty() && id != "0" {
                    return "generic/SKB";
                }
            }
        }
        "unknown"
    }

    #[cfg(not(all(target_os = "linux", feature = "tc_ebpf")))]
    pub fn new(_ifname: &str, _config: &Config) -> Result<Self> {
        Err("TC eBPF is only supported on Linux with tc_ebpf feature".into())
    }

    #[cfg(target_os = "linux")]
    fn get_ifindex(ifname: &str) -> Result<i32> {
        get_ifindex(ifname)
    }

    #[cfg(target_os = "linux")]
    fn check_kernel_version() -> Result<(u32, u32, u32)> {
        use std::ffi::CStr;
        let mut utsname: libc::utsname = unsafe { std::mem::zeroed() };
        if unsafe { libc::uname(&raw mut utsname) } != 0 {
            return Err("Failed to get kernel version".into());
        }
        let release = unsafe { CStr::from_ptr(utsname.release.as_ptr()) }
            .to_str()
            .unwrap_or("0.0.0");
        let parts: Vec<&str> = release.split(&['.', '-'][..]).collect();

        let major = parts
            .first()
            .and_then(|s| s.parse::<u32>().ok())
            .unwrap_or(0);
        let minor = parts
            .get(1)
            .and_then(|s| s.parse::<u32>().ok())
            .unwrap_or(0);
        let patch = parts
            .get(2)
            .and_then(|s| s.parse::<u32>().ok())
            .unwrap_or(0);

        Ok((major, minor, patch))
    }

    #[cfg(target_os = "linux")]
    fn read_iface_mac(ifname: &str) -> Result<[u8; 6]> {
        read_mac(ifname)
    }

    #[cfg(target_os = "linux")]
    fn read_iface_mtu(ifname: &str) -> Result<u16> {
        read_mtu(ifname)
    }

    #[cfg(target_os = "linux")]
    fn read_iface_gso_max_size(ifname: &str) -> Result<u32> {
        read_gso_max_size(ifname)
    }

    #[cfg(target_os = "linux")]
    fn set_iface_gso_max_size(ifname: &str, gso_max_size: u32) {
        link_set_gso_max_size(ifname, gso_max_size);
    }

    #[cfg(target_os = "linux")]
    fn default_route_ifname() -> Option<String> {
        // Parse /proc/net/route — no subprocess needed.
        // Fields: Iface Dest GW Flags RefCnt Use Metric Mask ...
        // Default route: Dest=00000000, Mask=00000000, RTF_UP(0x1)|RTF_GATEWAY(0x2).
        // IMPORTANT: use `let...else { continue }`, NOT `?`, inside the loop —
        // `?` would return None from the *function* on any malformed line.
        let content = std::fs::read_to_string("/proc/net/route").ok()?;
        let mut best: Option<(u32, String)> = None; // (metric, ifname)
        for line in content.lines().skip(1) {
            let mut f = line.split_whitespace();
            let Some(iface) = f.next() else { continue };
            let Some(dest) = f.next().and_then(|s| u32::from_str_radix(s, 16).ok()) else {
                continue;
            };
            f.next(); // GW
            let Some(flags) = f.next().and_then(|s| u32::from_str_radix(s, 16).ok()) else {
                continue;
            };
            f.next();
            f.next(); // RefCnt, Use
            let Some(metric) = f.next().and_then(|s| s.parse::<u32>().ok()) else {
                continue;
            };
            let Some(mask) = f.next().and_then(|s| u32::from_str_radix(s, 16).ok()) else {
                continue;
            };
            if dest == 0
                && mask == 0
                && (flags & 0x0003) == 0x0003
                && best.as_ref().is_none_or(|(m, _)| metric < *m)
            {
                best = Some((metric, iface.to_string()));
            }
        }
        best.map(|(_, iface)| iface)
    }

    /// Resolve routing info for `peer_ip` without any external binaries.
    ///
    /// - **src**: UDP `connect()` + `getsockname()` — the kernel picks the right source IP.
    /// - **dev**: parsed from `/proc/net/route` (IPv4) or `/proc/net/ipv6_route` (IPv6).
    /// - **via**: parsed from `/proc/net/route` (IPv4 gateway) or `/proc/net/ipv6_route` (IPv6 nexthop).
    /// - **mtu**: read from `/sys/class/net/<dev>/mtu` when dev is known.
    #[cfg(target_os = "linux")]
    fn route_get_info(peer_ip: std::net::IpAddr) -> Result<RouteGetInfo> {
        use std::net::{IpAddr, SocketAddr, UdpSocket};

        // ── 1. Resolve source IP via UDP connect trick ──────────────────────
        let src: Option<IpAddr> = (|| {
            let bind_addr: SocketAddr = match peer_ip {
                IpAddr::V4(_) => "0.0.0.0:0".parse().ok()?,
                IpAddr::V6(_) => "[::]:0".parse().ok()?,
            };
            let sock = UdpSocket::bind(bind_addr).ok()?;
            sock.connect(SocketAddr::new(peer_ip, 1)).ok()?;
            Some(sock.local_addr().ok()?.ip())
        })();

        // ── 2. Look up dev + via using Netlink (RTM_GETROUTE) ───────────────
        let (dev, via, mtu) = crate::netlink::nl_get_route(peer_ip).unwrap_or_else(|| {
            // Fallback to /proc/net/route if netlink fails
            match peer_ip {
                IpAddr::V4(target_v4) => Self::proc_route_lookup_v4(target_v4),
                IpAddr::V6(target_v6) => Self::proc_route_lookup_v6(target_v6),
            }
        });

        let first_line = format!(
            "{} dev {} src {}",
            peer_ip,
            dev.as_deref().unwrap_or("?"),
            src.map_or_else(|| "?".to_string(), |s| s.to_string())
        );

        Ok(RouteGetInfo {
            first_line,
            dev,
            via,
            src,
            mtu,
        })
    }

    /// Read `/proc/net/route` and find the best (longest-prefix) match for `target`.
    /// Returns `(dev, via, mtu)`.
    ///
    /// `/proc/net/route` stores addresses as hex of the raw `__be32` kernel value.
    /// On LE this prints as NE bytes; `u32::to_ne_bytes()` recovers the IP octets.
    #[cfg(target_os = "linux")]
    fn proc_route_lookup_v4(
        target: std::net::Ipv4Addr,
    ) -> (Option<String>, Option<std::net::IpAddr>, Option<u16>) {
        let Ok(content) = std::fs::read_to_string("/proc/net/route") else {
            return (None, None, None);
        };
        let nt = u32::from_ne_bytes(target.octets());
        let mut best_plen = -1i32;
        let mut best_dev: Option<String> = None;
        let mut best_gw: Option<std::net::Ipv4Addr> = None;
        for line in content.lines().skip(1) {
            let mut f = line.split_whitespace();
            let Some(dev) = f.next() else { continue };
            let Some(dest) = f.next().and_then(|s| u32::from_str_radix(s, 16).ok()) else {
                continue;
            };
            let Some(gw) = f.next().and_then(|s| u32::from_str_radix(s, 16).ok()) else {
                continue;
            };
            let Some(flags) = f.next().and_then(|s| u32::from_str_radix(s, 16).ok()) else {
                continue;
            };
            for _ in 0..3 {
                f.next();
            } // RefCnt, Use, Metric
            let Some(mask) = f.next().and_then(|s| u32::from_str_radix(s, 16).ok()) else {
                continue;
            };
            if flags & 1 == 0 || nt & mask != dest {
                continue;
            }
            let plen = mask.count_ones() as i32;
            if plen > best_plen {
                best_plen = plen;
                best_dev = Some(dev.to_string());
                // gw is a NE-hex u32; to_ne_bytes() gives IP octets in the right order.
                best_gw = if gw != 0 {
                    Some(std::net::Ipv4Addr::from(gw.to_ne_bytes()))
                } else {
                    None
                };
            }
        }
        let mtu = best_dev.as_deref().and_then(|d| {
            std::fs::read_to_string(format!("/sys/class/net/{d}/mtu"))
                .ok()?
                .trim()
                .parse()
                .ok()
        });
        (best_dev, best_gw.map(std::net::IpAddr::V4), mtu)
    }

    /// Read `/proc/net/ipv6_route` and find the best prefix match for `target`.
    /// Returns `(dev, via, mtu)`.
    ///
    /// Format (no header): dest_net/32hex prefix/2hex src_net src_prefix nexthop/32hex
    ///                     metric refcnt use flags/8hex iface
    #[cfg(target_os = "linux")]
    fn proc_route_lookup_v6(
        target: std::net::Ipv6Addr,
    ) -> (Option<String>, Option<std::net::IpAddr>, Option<u16>) {
        let Ok(content) = std::fs::read_to_string("/proc/net/ipv6_route") else {
            return (None, None, None);
        };
        let to = target.octets();
        let mut best_plen = -1i32;
        let mut best_dev: Option<String> = None;
        let mut best_nh: Option<std::net::Ipv6Addr> = None;
        for line in content.lines() {
            let c: Vec<&str> = line.split_whitespace().collect();
            if c.len() < 10 {
                continue;
            }
            let Some(dest_b) = hex16(c[0]) else { continue };
            let Ok(plen) = u8::from_str_radix(c[1], 16) else {
                continue;
            };
            let Ok(flags) = u32::from_str_radix(c[8], 16) else {
                continue;
            };
            if flags & 1 == 0 || plen > 128 {
                continue;
            }
            // Prefix match: full bytes then partial byte
            let fb = (plen / 8) as usize;
            let rb = plen % 8;
            if to[..fb] != dest_b[..fb] {
                continue;
            }
            if rb > 0 {
                let m = 0xFFu8 << (8 - rb);
                if to[fb] & m != dest_b[fb] & m {
                    continue;
                }
            }
            if plen as i32 > best_plen {
                best_plen = plen as i32;
                best_dev = Some(c[9].to_string());
                best_nh = hex16(c[4]).and_then(|b| {
                    let v = std::net::Ipv6Addr::from(b);
                    if v.is_unspecified() {
                        None
                    } else {
                        Some(v)
                    }
                });
            }
        }
        let mtu = best_dev.as_deref().and_then(|d| {
            std::fs::read_to_string(format!("/sys/class/net/{d}/mtu"))
                .ok()?
                .trim()
                .parse()
                .ok()
        });
        (best_dev, best_nh.map(std::net::IpAddr::V6), mtu)
    }

    #[cfg(target_os = "linux")]
    fn ensure_route_dev(
        peer_ip: std::net::IpAddr,
        ifname: &str,
        info: &RouteGetInfo,
    ) -> Result<()> {
        if let Some(route_dev) = info.dev.as_deref() {
            if route_dev != ifname {
                return Err(
                    format!("Route to {peer_ip} uses dev {route_dev}, expected {ifname}").into(),
                );
            }
        }
        Ok(())
    }

    /// Read the first IPv4 address assigned to `ifname` via /proc/net/fib_trie
    /// or `ip -4 addr show` (fallback). Used when peer_ip is dynamic (0.0.0.0)
    /// and route lookup would incorrectly return lo.
    #[cfg(target_os = "linux")]
    fn get_interface_ipv4(ifname: &str) -> Result<std::net::Ipv4Addr> {
        let output = std::process::Command::new("ip")
            .args(["-4", "-o", "addr", "show", "dev", ifname])
            .output()
            .map_err(|e| format!("failed to run ip addr show: {e}"))?;
        let stdout = String::from_utf8_lossy(&output.stdout);
        for line in stdout.lines() {
            // Format: "2: eth0    inet 172.18.0.2/16 brd ..."
            if let Some(inet_pos) = line.find("inet ") {
                let rest = &line[inet_pos + 5..];
                if let Some(slash) = rest.find('/') {
                    if let Ok(ip) = rest[..slash].parse::<std::net::Ipv4Addr>() {
                        if !ip.is_loopback() {
                            return Ok(ip);
                        }
                    }
                }
            }
        }
        Err(format!("no IPv4 address found on interface {ifname}").into())
    }

    /// Read the first global-scope IPv6 address on `ifname`.
    #[cfg(target_os = "linux")]
    fn get_interface_ipv6(ifname: &str) -> Result<std::net::Ipv6Addr> {
        let output = std::process::Command::new("ip")
            .args(["-6", "-o", "addr", "show", "dev", ifname, "scope", "global"])
            .output()
            .map_err(|e| format!("failed to run ip -6 addr show: {e}"))?;
        let stdout = String::from_utf8_lossy(&output.stdout);
        for line in stdout.lines() {
            if let Some(inet_pos) = line.find("inet6 ") {
                let rest = &line[inet_pos + 6..];
                if let Some(slash) = rest.find('/') {
                    if let Ok(ip) = rest[..slash].parse::<std::net::Ipv6Addr>() {
                        return Ok(ip);
                    }
                }
            }
        }
        Err(format!("no global IPv6 address found on interface {ifname}").into())
    }

    #[cfg(target_os = "linux")]
    fn resolve_l2_peer_ip(peer_ip: std::net::IpAddr, ifname: &str) -> Result<std::net::IpAddr> {
        let info = Self::route_get_info(peer_ip)?;
        Self::ensure_route_dev(peer_ip, ifname, &info)?;
        let l2_ip = info.via.unwrap_or(peer_ip);
        if info.dev.is_none() {
            eprintln!(
                "  [resolve-mac] /proc/net/route lookup for {peer_ip} returned no dev; \
                 using {l2_ip} as L2 target (may be wrong in L3 environments)"
            );
        }
        Ok(l2_ip)
    }

    #[cfg(target_os = "linux")]
    fn resolve_route_src_ip(peer_ip: std::net::IpAddr, ifname: &str) -> Result<std::net::IpAddr> {
        let info = Self::route_get_info(peer_ip)?;
        Self::ensure_route_dev(peer_ip, ifname, &info)?;
        info.src.ok_or_else(|| {
            format!(
                "No 'src' in route lookup for {peer_ip} on {ifname}. Output: {}",
                info.first_line
            )
            .into()
        })
    }

    #[cfg(target_os = "linux")]
    fn resolve_route_pmtu(peer_ip: std::net::IpAddr, ifname: &str) -> Result<u16> {
        let info = Self::route_get_info(peer_ip)?;
        Self::ensure_route_dev(peer_ip, ifname, &info)?;
        info.mtu
            .ok_or_else(|| format!("No explicit route PMTU for {peer_ip} on {ifname}").into())
    }

    #[cfg(target_os = "linux")]
    /// Send a single ICMP/ICMPv6 echo request to warm up the neighbor cache.
    /// Uses raw sockets via libc — no external binary needed.
    /// Failures are silently ignored (best-effort ARP/NDP probe).
    fn try_probe_neighbor(ip: std::net::IpAddr, ifname: &str) {
        match ip {
            std::net::IpAddr::V4(ipv4) => {
                Self::probe_icmp4(ipv4, ifname);
            }
            std::net::IpAddr::V6(ipv6) => {
                Self::probe_icmp6(ipv6, ifname);
            }
        }
    }

    fn probe_icmp4(dst: std::net::Ipv4Addr, ifname: &str) {
        use std::ffi::CString;
        unsafe {
            let sock = libc::socket(libc::AF_INET, libc::SOCK_RAW, libc::IPPROTO_ICMP);
            if sock < 0 {
                return;
            }
            // Bind to interface
            if let Ok(ifname_c) = CString::new(ifname) {
                libc::setsockopt(
                    sock,
                    libc::SOL_SOCKET,
                    libc::SO_BINDTODEVICE,
                    ifname_c.as_ptr() as *const libc::c_void,
                    (ifname.len() + 1) as libc::socklen_t,
                );
            }
            // Build minimal ICMP echo request (8 bytes)
            // type=8 code=0 checksum id=1 seq=1
            let mut pkt = [0u8; 8];
            pkt[0] = 8; // ICMP_ECHO
            pkt[6] = 0;
            pkt[7] = 1; // seq=1
                        // checksum
            let sum = Self::icmp_checksum(&pkt);
            pkt[2] = (sum >> 8) as u8;
            pkt[3] = (sum & 0xff) as u8;
            let octets = dst.octets();
            let dst_addr = libc::sockaddr_in {
                sin_family: libc::AF_INET as libc::sa_family_t,
                sin_port: 0,
                sin_addr: libc::in_addr {
                    s_addr: u32::from_ne_bytes(octets),
                },
                sin_zero: [0; 8],
            };
            libc::sendto(
                sock,
                pkt.as_ptr() as *const libc::c_void,
                pkt.len(),
                libc::MSG_DONTWAIT,
                &raw const dst_addr as *const libc::sockaddr,
                std::mem::size_of::<libc::sockaddr_in>() as libc::socklen_t,
            );
            libc::close(sock);
        }
    }

    fn probe_icmp6(dst: std::net::Ipv6Addr, ifname: &str) {
        use std::ffi::CString;
        unsafe {
            let sock = libc::socket(libc::AF_INET6, libc::SOCK_RAW, libc::IPPROTO_ICMPV6);
            if sock < 0 {
                return;
            }
            if let Ok(ifname_c) = CString::new(ifname) {
                libc::setsockopt(
                    sock,
                    libc::SOL_SOCKET,
                    libc::SO_BINDTODEVICE,
                    ifname_c.as_ptr() as *const libc::c_void,
                    (ifname.len() + 1) as libc::socklen_t,
                );
            }
            // ICMPv6 echo request — kernel computes checksum for SOCK_RAW+ICMPV6
            // type=128 code=0 checksum=0 id=1 seq=1
            let pkt = [128u8, 0, 0, 0, 0, 1, 0, 1];
            let octets = dst.octets();
            let dst_addr = libc::sockaddr_in6 {
                sin6_family: libc::AF_INET6 as libc::sa_family_t,
                sin6_port: 0,
                sin6_flowinfo: 0,
                sin6_addr: libc::in6_addr { s6_addr: octets },
                sin6_scope_id: 0,
            };
            libc::sendto(
                sock,
                pkt.as_ptr() as *const libc::c_void,
                pkt.len(),
                libc::MSG_DONTWAIT,
                &raw const dst_addr as *const libc::sockaddr,
                std::mem::size_of::<libc::sockaddr_in6>() as libc::socklen_t,
            );
            libc::close(sock);
        }
    }

    fn icmp_checksum(data: &[u8]) -> u16 {
        let mut sum: u32 = 0;
        let mut i = 0;
        while i + 1 < data.len() {
            sum += u32::from(u16::from_be_bytes([data[i], data[i + 1]]));
            i += 2;
        }
        if i < data.len() {
            sum += u32::from(data[i]) << 8;
        }
        while sum >> 16 != 0 {
            sum = (sum & 0xffff) + (sum >> 16);
        }
        !(sum as u16)
    }

    #[cfg(target_os = "linux")]
    fn resolve_peer_mac(peer_ip: std::net::IpAddr, ifname: &str) -> Result<[u8; 6]> {
        let l2_ip = Self::resolve_l2_peer_ip(peer_ip, ifname).unwrap_or(peer_ip);

        // Probe every 2 attempts to avoid flooding, retry for up to ~2 s total.
        for attempt in 0..6 {
            // First, actively try to get a response directly via ARP request (bypassing caches)
            match l2_ip {
                std::net::IpAddr::V4(v4) => {
                    if let Some(mac) = crate::netlink::arp_request_reply(v4, ifname) {
                        return Ok(mac);
                    }
                }
                std::net::IpAddr::V6(v6) => {
                    if let Some(mac) = crate::netlink::ndp_request_reply(v6, ifname) {
                        return Ok(mac);
                    }
                }
            }

            let mac = match l2_ip {
                std::net::IpAddr::V4(v4) => Self::lookup_arp_cache(v4, ifname),
                std::net::IpAddr::V6(v6) => Self::lookup_ndp_cache(v6, ifname),
            };
            if let Some(mac) = mac {
                return Ok(mac);
            }

            if attempt % 2 == 0 {
                // UDP connect triggers kernel ARP/NDP without requiring NET_RAW.
                probe_neighbor_udp(l2_ip, ifname);
                // Also try raw ICMP as a secondary probe (best-effort).
                Self::try_probe_neighbor(l2_ip, ifname);
            }
            std::thread::sleep(std::time::Duration::from_millis(300));
        }

        // Fallback: ARP/NDP resolution failed (common in L3-routed environments like
        // RouterOS where containers are on separate veths without a shared L2 bridge).
        // The actual next-hop is the default gateway — use its MAC instead.
        let peer_v4 = if let std::net::IpAddr::V4(v4) = l2_ip {
            Some(v4)
        } else {
            None
        };
        if let Some(gw_mac) = Self::resolve_default_gateway_mac(ifname, peer_v4) {
            eprintln!(
                "  ARP for {l2_ip} (peer {peer_ip}) failed; using default gateway MAC \
                 {:02x?} on {ifname}",
                gw_mac
            );
            return Ok(gw_mac);
        }

        Err(format!(
            "No neighbor entry for route next-hop {l2_ip} (peer {peer_ip}) on interface {ifname}. \
            Hint: check /proc/net/arp or /proc/net/if_inet6 on the host."
        )
        .into())
    }

    /// Resolve the default gateway MAC on `ifname`.
    /// Used as fallback when direct ARP fails in L3-routed environments.
    ///
    /// `peer_hint` — a peer IPv4 address used as the TTL-probe packet destination.
    /// Providing it improves reliability in environments where ARP is suppressed.
    #[cfg(target_os = "linux")]
    fn resolve_default_gateway_mac(
        ifname: &str,
        peer_hint: Option<std::net::Ipv4Addr>,
    ) -> Option<[u8; 6]> {
        // Read default gateway from /proc/net/route (dest=0, mask=0, gw!=0).
        //
        // IMPORTANT: all `?` inside the `for` loop would return `None` from the
        // whole function on any parse error (e.g., empty trailing line).  Use
        // `let Some(...) = ... else { continue }` everywhere inside the loop.
        let Ok(content) = std::fs::read_to_string("/proc/net/route") else {
            eprintln!("  [gw-mac] /proc/net/route not readable");
            return None;
        };
        let mut gw_exact: Option<std::net::Ipv4Addr> = None; // matches ifname
        let mut gw_any: Option<std::net::Ipv4Addr> = None; // any interface
        for line in content.lines().skip(1) {
            let mut f = line.split_whitespace();
            let Some(iface) = f.next() else { continue };
            let Some(dest) = f.next().and_then(|s| u32::from_str_radix(s, 16).ok()) else {
                continue;
            };
            let Some(gw) = f.next().and_then(|s| u32::from_str_radix(s, 16).ok()) else {
                continue;
            };
            let Some(flags) = f.next().and_then(|s| u32::from_str_radix(s, 16).ok()) else {
                continue;
            };
            for _ in 0..3 {
                f.next();
            } // skip RefCnt, Use, Metric
            let Some(mask) = f.next().and_then(|s| u32::from_str_radix(s, 16).ok()) else {
                continue;
            };
            // Default route: dest=0/0, GATEWAY flag (0x2) + UP flag (0x1) set, gw != 0
            if dest == 0 && mask == 0 && flags & 0x3 == 0x3 && gw != 0 {
                let ip = std::net::Ipv4Addr::from(gw.to_ne_bytes());
                if iface == ifname {
                    gw_exact = Some(ip);
                    break; // exact interface match — stop searching
                } else if gw_any.is_none() {
                    gw_any = Some(ip); // keep as fallback
                }
            }
        }
        let gw = match gw_exact.or(gw_any) {
            Some(ip) => ip,
            None => {
                eprintln!("  [gw-mac] no default gateway found in /proc/net/route for {ifname}");
                return None;
            }
        };
        eprintln!("  [gw-mac] probing gateway {gw} on {ifname}");
        // Method 1: ARP Request + receive reply directly via AF_PACKET.
        // Works even when /proc/net/arp and RTM_GETNEIGH are empty (RouterOS containers).
        if let Some(mac) = crate::netlink::arp_request_reply(gw, ifname) {
            eprintln!(
                "  [gw-mac] gateway MAC resolved via ARP reply: {:02x?}",
                mac
            );
            return Some(mac);
        }
        // Method 2: TTL=1 IP probe via AF_PACKET → read MAC from ICMP TTL-Exceeded reply.
        // Bypasses ARP entirely — useful when the gateway silently ignores ARP requests
        // (e.g. RouterOS bridges with ARP suppression or proxy ARP on the host side).
        // We send a broadcast-MAC UDP frame (TTL=1) to `probe_dst_ip`; the gateway
        // forwards it, hits TTL=0, and sends ICMP back — revealing its own L2 MAC.
        let probe_dst = peer_hint.unwrap_or_else(|| {
            // No peer hint — pick an address in the same /24 that the gateway
            // is unlikely to be itself, so the frame is actually forwarded.
            let [a, b, c, _] = gw.octets();
            std::net::Ipv4Addr::new(a, b, c, 200)
        });
        if let Some(mac) = crate::netlink::resolve_mac_via_ttl_probe(gw, probe_dst, ifname) {
            eprintln!(
                "  [gw-mac] gateway MAC resolved via TTL probe: {:02x?}",
                mac
            );
            return Some(mac);
        }
        // Method 3: UDP-triggered kernel ARP + RTM_GETNEIGH.
        // Used when CAP_NET_RAW is absent (AF_PACKET unavailable).
        let gw_addr = std::net::IpAddr::V4(gw);
        for _ in 0..8 {
            if let Some(mac) = lookup_arp_cache(gw, ifname) {
                return Some(mac);
            }
            probe_neighbor_udp(gw_addr, ifname);
            std::thread::sleep(std::time::Duration::from_millis(250));
        }
        // Diagnostic: dump /proc/net/arp to help understand why lookup failed
        match std::fs::read_to_string("/proc/net/arp") {
            Ok(arp) if !arp.trim().is_empty() => {
                eprintln!("  [gw-mac] /proc/net/arp:\n{arp}");
            }
            _ => eprintln!("  [gw-mac] /proc/net/arp: empty or unreadable"),
        }
        eprintln!("  [gw-mac] ARP for gateway {gw} on {ifname} failed after retries");
        None
    }

    /// Look up an IPv4 MAC from the kernel ARP cache.
    #[cfg(target_os = "linux")]
    fn lookup_arp_cache(ip: std::net::Ipv4Addr, ifname: &str) -> Option<[u8; 6]> {
        lookup_arp_cache(ip, ifname)
    }

    /// Look up an IPv6 neighbor MAC via RTM_GETNEIGH netlink.
    #[cfg(target_os = "linux")]
    fn lookup_ndp_cache(ip: std::net::Ipv6Addr, ifname: &str) -> Option<[u8; 6]> {
        lookup_ndp_cache(ip, ifname)
    }

    #[cfg(target_os = "linux")]
    fn build_gut_config(
        config: &Config,
        tun_ifname: &str,
        ingress_ifname: &str,
    ) -> Result<GutConfig> {
        let mut gut_config = GutConfig::from_config(
            &config.peer().key,
            &config.peer().ports,
            config.peer().peer_ip,
            config.peer().outer_mtu,
        );

        // Set bind address (v4 and/or v6).
        // If wildcard bind is configured (0.0.0.0 / ::), resolve concrete
        // source IP from the route to peer_ip on ingress_ifname.
        // When peer_ip is unspecified (dynamic mode), route lookup to 0.0.0.0
        // returns lo — fall back to reading the address directly from the NIC.
        let peer_ip_for_route = config.peer().peer_ip;
        let use_iface_addr = peer_ip_for_route.is_unspecified();

        match config.peer().bind_ip {
            std::net::IpAddr::V4(ip) => {
                if ip.is_unspecified() {
                    let src = if use_iface_addr {
                        Self::get_interface_ipv4(ingress_ifname)?
                    } else {
                        match Self::resolve_route_src_ip(peer_ip_for_route, ingress_ifname)? {
                            std::net::IpAddr::V4(v4) => v4,
                            std::net::IpAddr::V6(v6) => {
                                return Err(format!(
                                    "bind_ip=0.0.0.0 but route source resolved to IPv6 {}. \
                                     Set explicit bind_ip or peer_ip family consistently.",
                                    v6
                                )
                                .into());
                            }
                        }
                    };
                    gut_config.bind_ip = u32::from_ne_bytes(src.octets());
                    eprintln!(
                        "  bind_ip auto-resolved: 0.0.0.0 → {} ({})",
                        src,
                        if use_iface_addr {
                            format!("interface addr on {}", ingress_ifname)
                        } else {
                            format!("route src on {}", ingress_ifname)
                        }
                    );
                } else {
                    gut_config.bind_ip = u32::from_ne_bytes(ip.octets());
                }
            }
            std::net::IpAddr::V6(ip) => {
                if ip.is_unspecified() {
                    let src = if use_iface_addr {
                        Self::get_interface_ipv6(ingress_ifname)?
                    } else {
                        match Self::resolve_route_src_ip(peer_ip_for_route, ingress_ifname)? {
                            std::net::IpAddr::V6(v6) => v6,
                            std::net::IpAddr::V4(v4) => {
                                return Err(format!(
                                    "bind_ip=:: but route source resolved to IPv4 {}. \
                                     Set explicit bind_ip or peer_ip family consistently.",
                                    v4
                                )
                                .into());
                            }
                        }
                    };
                    gut_config.bind_ip6 = src.octets();
                    eprintln!(
                        "  bind_ip auto-resolved: :: → {} ({})",
                        src,
                        if use_iface_addr {
                            format!("interface addr on {}", ingress_ifname)
                        } else {
                            format!("route src on {}", ingress_ifname)
                        }
                    );
                } else {
                    gut_config.bind_ip6 = ip.octets();
                }
            }
        }
        gut_config.egress_ifindex = Self::get_ifindex(ingress_ifname)? as u32;
        gut_config.tun_ifindex = Self::get_ifindex(tun_ifname)? as u32;
        gut_config.src_mac = Self::read_iface_mac(ingress_ifname)?;
        if config.peer().dynamic_peer {
            // Dynamic peer: can't ARP for unknown peer. Use default gateway MAC.
            gut_config.dst_mac = Self::resolve_default_gateway_mac(ingress_ifname, None)
                .ok_or("dynamic_peer: cannot resolve default gateway MAC on ingress NIC")?;
        } else {
            gut_config.dst_mac = Self::resolve_peer_mac(config.peer().peer_ip, ingress_ifname)?;
        }
        gut_config.tun_mac = Self::read_iface_mac(tun_ifname).unwrap_or([0; 6]);

        // Set default XDP action from config.
        // Safety guard: DROP on the default-route NIC can blackhole host traffic
        // (including SSH). Auto-downgrade to PASS in that case.
        gut_config.default_xdp_action = match config.peer().default_policy {
            crate::config::XdpDefaultPolicy::Allow => 0, // XDP_PASS
            crate::config::XdpDefaultPolicy::Drop => 1,  // XDP_DROP
        };
        gut_config.keepalive_drop_percent = config.peer().keepalive_drop_percent;
        gut_config.own_http3 = if config.peer().own_http3 { 1 } else { 0 };

        if gut_config.default_xdp_action == 1 {
            if let Some(default_ifname) = Self::default_route_ifname() {
                if default_ifname == ingress_ifname {
                    eprintln!(
                        "WARNING: default_policy=drop on ingress NIC '{}' (default route). \
                         Without this guard, all non-GUT ingress traffic on this NIC would be dropped \
                         (including SSH/management). For safety, overriding to allow.",
                        ingress_ifname
                    );
                    DROP_POLICY_SAFETY_OVERRIDES.fetch_add(1, Ordering::Relaxed);
                    gut_config.default_xdp_action = 0;
                }
            }
        }

        let route_pmtu = Self::resolve_route_pmtu(config.peer().peer_ip, ingress_ifname).ok();
        let ingress_mtu = Self::read_iface_mtu(ingress_ifname).ok();
        let pmtu_base = route_pmtu
            .or(ingress_mtu)
            .unwrap_or(config.peer().outer_mtu);
        gut_config.outer_mtu = pmtu_base;
        let computed_v4 = pmtu_base.saturating_sub(OUTER_OVERHEAD_IPV4);
        let computed_v6 = pmtu_base.saturating_sub(OUTER_OVERHEAD_IPV6);
        gut_config.inner_mtu_v4 = if computed_v4 == 0 {
            DEFAULT_INNER_MTU
        } else {
            computed_v4
        };
        gut_config.inner_mtu_v6 = if computed_v6 == 0 {
            DEFAULT_INNER_MTU
        } else {
            computed_v6
        };
        let inner_v4 = gut_config.inner_mtu_v4;
        let inner_v6 = gut_config.inner_mtu_v6;
        let wg_data_overhead: u16 = 32;
        let wg_rec_v4 = inner_v4.saturating_sub(wg_data_overhead);
        let wg_rec_v6 = inner_v6.saturating_sub(wg_data_overhead);

        eprintln!(
            "GUT TC eBPF PMTU: base={} inner_v4={} inner_v6={} (base=route_pmtu|if_mtu|config_outer_mtu)",
            pmtu_base, inner_v4, inner_v6
        );
        eprintln!(
            "GUT TC eBPF WG MTU recommendation: ipv4={} ipv6={} (WG data overhead=32, payload-only mode)",
            wg_rec_v4, wg_rec_v6
        );

        gut_config.offload_flags = Self::probe_offload_flags(tun_ifname);

        // Partial IP checksum only meaningful for outer IPv4
        if config.peer().peer_ip.is_ipv4() {
            gut_config.compute_partial_ip_csum();
        }

        // Populate tunnel veth IPs for XDP ingress IP rewrite.
        // XDP rewrites outer src/dst back to gut0 IPs so WireGuard does not
        // roam to the real remote IP after receiving the first ingress packet.
        match crate::tun::compute_p2p_peer(&config.peer().address) {
            Ok((local_ip_str, peer_ip_str, _)) => {
                match (
                    local_ip_str.parse::<std::net::Ipv4Addr>(),
                    peer_ip_str.parse::<std::net::Ipv4Addr>(),
                ) {
                    (Ok(local_ip), Ok(peer_ip)) => {
                        gut_config.tun_local_ip4 = u32::from_ne_bytes(local_ip.octets());
                        gut_config.tun_peer_ip4 = u32::from_ne_bytes(peer_ip.octets());
                        eprintln!(
                            "  XDP ingress IP rewrite: src={} dst={} (tun_peer → tun_local)",
                            peer_ip, local_ip
                        );
                    }
                    _ => {
                        eprintln!(
                            "  WARNING: XDP ingress IP rewrite disabled \
                             (address={} is IPv6 or unparseable)",
                            config.peer().address
                        );
                    }
                }
            }
            Err(e) => {
                eprintln!(
                    "  WARNING: XDP ingress IP rewrite disabled \
                     (compute_p2p_peer failed: {e})"
                );
            }
        }

        // Dynamic peer mode flag
        if config.peer().dynamic_peer {
            gut_config.dynamic_peer = 1;
            eprintln!("  Dynamic peer mode: endpoint will be learned from inbound packets");
        }

        // Obfuscation mode
        match config.peer().obfs {
            crate::config::ObfsMode::Gut => {
                gut_config.obfs_gut = 1;
                eprintln!("  Obfuscation mode: gut (BPF per-mode)");
            }
            crate::config::ObfsMode::Quic => {
                eprintln!("  Obfuscation mode: quic (BPF per-mode)");
            }
            crate::config::ObfsMode::Syslog => {
                eprintln!("  Obfuscation mode: syslog (BPF per-mode)");
            }
            crate::config::ObfsMode::Sip => {
                eprintln!("  Obfuscation mode: sip (BPF per-mode)");
            }
        }

        // ── QUIC AEAD: precompute keys from fixed DCID so BPF only needs AES-GCM ──
        {
            // Fixed DCID derived from GUT key (ChaCha block 99, nonce 0)
            let chacha_init = gut_config.chacha_init;
            let chacha_rounds = gut_config.chacha_rounds;
            let ks99 =
                crate::proto::mask_balanced::chacha_block_fast(&chacha_init, 99, 0, chacha_rounds);
            gut_config.quic_dcid[0..4].copy_from_slice(&ks99[0].to_le_bytes());
            gut_config.quic_dcid[4..8].copy_from_slice(&ks99[1].to_le_bytes());

            // QUIC v1 key derivation: DCID → Initial Secret → Client Secret → keys
            let initial_secret =
                crate::proto::quic::derive_quic_initial_secret(&gut_config.quic_dcid);
            let client_secret = crate::proto::quic::derive_client_initial_secret(&initial_secret);
            let (q_key, q_iv, q_hp) = crate::proto::quic::derive_quic_keys(&client_secret);
            gut_config.quic_key_rk = crate::crypto::aes128_expand_key(&q_key);
            gut_config.quic_hp_rk = crate::crypto::aes128_expand_key(&q_hp);
            gut_config.quic_iv = q_iv;

            // SNI domain (= sip_domain from config), space-padded to 32 for fixed-size BPF syslog header
            let sni = config.peer().sip_domain.as_bytes();
            let sni_len = sni.len().min(31);
            gut_config.sni_domain[..sni_len].copy_from_slice(&sni[..sni_len]);
            // Pad remaining bytes with spaces so syslog header has no null bytes
            for b in &mut gut_config.sni_domain[sni_len..] {
                *b = b' ';
            }
            gut_config.sni_domain_len = sni_len as u8;

            eprintln!(
                "  QUIC AEAD: dcid={:02x}{:02x}{:02x}{:02x}{:02x}{:02x}{:02x}{:02x} sni=\"{}\"",
                gut_config.quic_dcid[0],
                gut_config.quic_dcid[1],
                gut_config.quic_dcid[2],
                gut_config.quic_dcid[3],
                gut_config.quic_dcid[4],
                gut_config.quic_dcid[5],
                gut_config.quic_dcid[6],
                gut_config.quic_dcid[7],
                &config.peer().sip_domain,
            );
        }

        Ok(gut_config)
    }

    #[cfg(target_os = "linux")]
    fn probe_offload_flags(ifname: &str) -> u16 {
        let disable_l4_csum = std::env::var("GUTD_FORCE_L4_CSUM")
            .ok()
            .map(|v| matches!(v.as_str(), "0" | "false" | "no" | "off"))
            .unwrap_or(false);

        if disable_l4_csum {
            eprintln!(
                "  offloads: {ifname} \u{2192} forced inner L4 finalize disabled (GUTD_FORCE_L4_CSUM=0)"
            );
            0
        } else {
            eprintln!(
                "  offloads: {ifname} \u{2192} BPF finalizes inner L4 checksum (default); \
                 set GUTD_FORCE_L4_CSUM=0 only for troubleshooting"
            );
            GUT_FLAG_NEED_L4_CSUM
        }
    }

    #[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
    pub fn update_config(&mut self, config: &Config) -> Result<()> {
        let gut_config = Self::build_gut_config(config, &self.interface, &self.ingress_interface)?;

        self.egress_skel.update_config_map(&gut_config)?;

        let outer_af = if self.egress_skel.is_v6() {
            "IPv6"
        } else {
            "IPv4"
        };
        eprintln!(
            "GUT TC eBPF: Config reloaded (egress={}, ingress={}, outer={}, obfs={:?})",
            self.interface,
            self.ingress_interface,
            outer_af,
            config.peer().obfs
        );
        Ok(())
    }

    #[cfg(not(all(target_os = "linux", feature = "tc_ebpf")))]
    pub fn update_config(&mut self, _config: &Config) -> Result<()> {
        Err("TC eBPF not available on this platform".into())
    }

    #[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
    pub fn get_stats(&self) -> Result<TcStats> {
        let key = 0u32.to_ne_bytes();
        let value_size = std::mem::size_of::<GutStats>();

        let egress = match self.egress_skel.lookup_stats(&key)? {
            Some(ref per_cpu) => Self::parse_percpu_stats(per_cpu, value_size),
            None => GutStats::default(),
        };

        let ingress = Self::lookup_percpu_raw(self.ingress_stats_fd, &key, value_size)
            .map(|per_cpu| Self::parse_percpu_stats(&per_cpu, value_size))
            .unwrap_or_default();

        let debug = self
            .egress_skel
            .get_map_fd("tc_debug_map")
            .and_then(|fd| Self::lookup_array_raw(fd.as_raw_fd(), &key, std::mem::size_of::<TcDebugStats>()))
            .map(|bytes| Self::parse_tc_debug_stats(&bytes))
            .unwrap_or_default();

        Ok(TcStats { egress, ingress, debug })
    }

    #[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
    fn lookup_array_raw(map_fd: i32, key: &[u8], value_size: usize) -> Option<Vec<u8>> {
        let mut buf = vec![0u8; value_size];
        let ret = unsafe {
            libbpf_sys::bpf_map_lookup_elem(map_fd, key.as_ptr().cast(), buf.as_mut_ptr().cast())
        };
        if ret < 0 {
            return None;
        }
        Some(buf)
    }

    /// Read a PERCPU_ARRAY map entry by raw FD.
    #[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
    fn lookup_percpu_raw(map_fd: i32, key: &[u8], value_size: usize) -> Option<Vec<Vec<u8>>> {
        let num_cpus = unsafe { libbpf_sys::libbpf_num_possible_cpus() } as usize;
        if num_cpus == 0 {
            return None;
        }
        // Kernel requires values aligned to 8 bytes per CPU.
        let aligned = (value_size + 7) & !7;
        let mut buf = vec![0u8; num_cpus * aligned];
        let ret = unsafe {
            libbpf_sys::bpf_map_lookup_elem(map_fd, key.as_ptr().cast(), buf.as_mut_ptr().cast())
        };
        if ret < 0 {
            return None;
        }
        let per_cpu: Vec<Vec<u8>> = (0..num_cpus)
            .map(|i| buf[i * aligned..i * aligned + value_size].to_vec())
            .collect();
        Some(per_cpu)
    }

    /// Parse per-CPU values returned by `lookup_percpu()`. Returns aggregated stats.
    #[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
    fn parse_percpu_stats(per_cpu_data: &[Vec<u8>], value_size: usize) -> GutStats {
        let mut per_cpu = Vec::with_capacity(per_cpu_data.len());
        for cpu_data in per_cpu_data {
            if cpu_data.len() >= value_size {
                let mut stats = GutStats::default();
                unsafe {
                    std::ptr::copy_nonoverlapping(
                        cpu_data.as_ptr(),
                        (&raw mut stats).cast::<u8>(),
                        value_size,
                    );
                }
                per_cpu.push(stats);
            }
        }
        GutStats::aggregate(&per_cpu)
    }

    #[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
    fn parse_tc_debug_stats(data: &[u8]) -> TcDebugStats {
        let mut stats = TcDebugStats::default();
        if data.len() >= std::mem::size_of::<TcDebugStats>() {
            unsafe {
                std::ptr::copy_nonoverlapping(
                    data.as_ptr(),
                    (&raw mut stats).cast::<u8>(),
                    std::mem::size_of::<TcDebugStats>(),
                );
            }
        }
        stats
    }

    #[cfg(not(all(target_os = "linux", feature = "tc_ebpf")))]
    pub fn get_stats(&self) -> Result<TcStats> {
        Ok(TcStats::default())
    }

    #[must_use]
    pub fn interface(&self) -> &str {
        &self.interface
    }
}

impl Drop for TcBpfManager {
    fn drop(&mut self) {
        eprintln!(
            "GUT TC eBPF: Detaching (egress={}, ingress={})",
            self.interface, self.ingress_interface,
        );

        #[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
        {
            eprintln!("  Destroying veth pair: {}", self._veth_xdp_name);
            crate::tun::destroy_veth(&self._veth_xdp_name);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[cfg(target_os = "linux")]
    fn test_kernel_version() {
        let version = TcBpfManager::check_kernel_version().unwrap();
        eprintln!("Kernel version: {}.{}.{}", version.0, version.1, version.2);
        assert!(version.0 >= 4);
    }

    #[test]
    fn test_deterministic_mac_generation() {
        let mac1 = crate::tun::mac_from_ipv4("10.0.0.1").unwrap();
        let mac2 = crate::tun::mac_from_ipv4("10.0.0.1").unwrap();

        // Deterministic: same input → same output
        assert_eq!(mac1, mac2);

        // Locally-administered bit set
        assert_eq!(mac1[0] & 0x02, 0x02);

        // Unicast (multicast bit clear)
        assert_eq!(mac1[0] & 0x01, 0x00);

        // GUT marker byte
        assert_eq!(mac1[1], 0x47);

        // IP octets embedded directly
        assert_eq!(mac1, [0x02, 0x47, 10, 0, 0, 1]);

        // Different IPs → different MACs
        let mac3 = crate::tun::mac_from_ipv4("10.0.0.2").unwrap();
        assert_ne!(mac1, mac3);

        eprintln!(
            "MAC 10.0.0.1: {} | MAC 10.0.0.2: {}",
            crate::tun::mac_to_string(&mac1),
            crate::tun::mac_to_string(&mac3)
        );
    }

    #[test]
    #[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
    fn test_gut_v1_protocol() {
        eprintln!("GUT v1 Protocol - TC eBPF fast path enabled");
        eprintln!("Wire format: QUIC Wrapper");
    }

    /// Open all BPF skeletons (ELF parsing, BTF validation, map definitions).
    /// Runs without privileges. If CAP_BPF is available, also runs the kernel
    /// verifier via `load()`.
    #[test]
    #[cfg(all(target_os = "linux", feature = "tc_ebpf"))]
    fn test_bpf_verifier() {
        use libbpf_rs::skel::{OpenSkel, SkelBuilder};
        use std::mem::MaybeUninit;

        let names = [
            "tc_gut_egress (v4)",
            "tc_gut_egress (v6)",
            "xdp_gut_ingress",
        ];
        let mut kernel_verified = 0usize;

        // --- tc_gut_egress v4 ---
        {
            let obj = Box::leak(Box::new(MaybeUninit::uninit()));
            let open = super::tc_gut_egress_quic::TcGutEgressSkelBuilder::default()
                .open(obj)
                .expect("tc_gut_egress (v4) open failed");
            match open.load() {
                Ok(_) => {
                    eprintln!("  {} — open + verifier PASS", names[0]);
                    kernel_verified += 1;
                }
                Err(e) if e.to_string().to_lowercase().contains("perm") => {
                    eprintln!("  {} — open PASS, verifier skipped (no CAP_BPF)", names[0]);
                }
                Err(e) => panic!("{} verifier FAILED: {e}", names[0]),
            }
        }

        // --- tc_gut_egress v6 ---
        {
            let obj = Box::leak(Box::new(MaybeUninit::uninit()));
            let open = super::tc_gut_egress_quic_v6::TcGutEgressSkelBuilder::default()
                .open(obj)
                .expect("tc_gut_egress (v6) open failed");
            match open.load() {
                Ok(_) => {
                    eprintln!("  {} — open + verifier PASS", names[1]);
                    kernel_verified += 1;
                }
                Err(e) if e.to_string().to_lowercase().contains("perm") => {
                    eprintln!("  {} — open PASS, verifier skipped (no CAP_BPF)", names[1]);
                }
                Err(e) => panic!("{} verifier FAILED: {e}", names[1]),
            }
        }

        // --- xdp_gut_ingress (quic) ---
        {
            let obj = Box::leak(Box::new(MaybeUninit::uninit()));
            let open = super::xdp_gut_ingress_quic::XdpGutIngressSkelBuilder::default()
                .open(obj)
                .expect("xdp_gut_ingress open failed");
            match open.load() {
                Ok(_) => {
                    eprintln!("  {} — open + verifier PASS", names[2]);
                    kernel_verified += 1;
                }
                Err(e) if e.to_string().to_lowercase().contains("perm") => {
                    eprintln!("  {} — open PASS, verifier skipped (no CAP_BPF)", names[2]);
                }
                Err(e) => panic!("{} verifier FAILED: {e}", names[2]),
            }
        }

        if kernel_verified == names.len() {
            eprintln!("All {} BPF programs passed kernel verifier", names.len());
        } else {
            eprintln!("ELF/BTF validation passed. Run with sudo for full kernel verifier check.");
        }
    }
}
